input=input("Enter number from 1 to 12: ")
if input=="1":print("January")
elif input=="2":print("February")
elif input=="3":print("March")
elif input=="4":print("April")
elif input=="5":print("May")
elif input=="6":print("June")
elif input=="7":print("July")
elif input=="8":print("August")
elif input=="9":print("September")
elif input=="10":print("October")
elif input=="11":print("November")
elif input=="12":print("December")
else:print("You made a mistake, repeat with numbers from 1 to 12")